<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HIH-D-752" name="UserStory_课程主页相关操作_陈侃" tests="1" failures="1" timestamp="30 Sep 2014 02:25:13 GMT" time="57.884" errors="0">
  <testcase name="testFruit" time="57.84" classname="per.jacobs.seed.test.SeedTest">
    <failure type="java.lang.AssertionError" message="Failed to find element //hadf &amp;gt;&amp;gt; capture screenshot at Failed to screenshot">
      <![CDATA[java.lang.AssertionError: Failed to find element //hadf >> capture screenshot at Failed to screenshot
	at org.testng.Assert.fail(Assert.java:94)
	at per.jacobs.seed.driver.SeedDriver.handleFailure(SeedDriver.java:318)
	at per.jacobs.seed.driver.SeedDriver.expectElementExistOrNot(SeedDriver.java:239)
	at per.jacobs.seed.driver.SeedDriver.click(SeedDriver.java:87)
	at per.jacobs.seed.Fruit.click(Fruit.java:96)
	at per.jacobs.seed.test.SeedTest.testFruit(SeedTest.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNoExecutor(MethodInvocationHelper.java:240)
	at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:229)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:724)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- testFruit -->
</testsuite> <!-- UserStory_课程主页相关操作_陈侃 -->
